// Collection of quotes for typing practice
const quotes = [
    "The only way to do great work is to love what you do.",
    "Life is what happens when you're busy making other plans.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Believe you can and you're halfway there.",
    "The best way to predict the future is to create it.",
    "Everything you can imagine is real.",
    "If you want to lift yourself up, lift up someone else.",
    "The purpose of our lives is to be happy.",
    "You only live once, but if you do it right, once is enough.",
    "Life is really simple, but we insist on making it complicated.",
    "The journey of a thousand miles begins with one step.",
    "What we think, we become.",
    "The only impossible journey is the one you never begin.",
    "If life were predictable it would cease to be life, and be without flavor.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "The way to get started is to quit talking and begin doing.",
    "Your time is limited, so don't waste it living someone else's life.",
    "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.",
    "Life is never fair, and perhaps it is a good thing for most of us that it is not.",
    "The only impossible journey is the one you never begin.",
    "In this life we cannot do great things. We can only do small things with great love.",
    "Only a life lived for others is a life worthwhile.",
    "The purpose of our lives is to be happy.",
    "Keep smiling, because life is a beautiful thing and there's so much to smile about.",
    "Many of life's failures are people who did not realize how close they were to success when they gave up.",
    "You miss 100% of the shots you don't take.",
    "I have failed over and over and over again in my life. And that is why I succeed.",
    "The question isn't who is going to let me; it's who is going to stop me.",
    "I attribute my success to this: I never gave or took any excuse.",
    "You can never cross the ocean until you have the courage to lose sight of the shore.",
    "I've missed more than 9,000 shots in my career. I've lost almost 300 games. 26 times I've been trusted to take the game winning shot and missed. I've failed over and over and over again in my life, and that is why I succeed.",
    "The most difficult thing is the decision to act, the rest is merely tenacity.",
    "Every strike brings me closer to the next home run.",
    "The mind is everything. What you think you become.",
    "Innovation distinguishes between a leader and a follower.",
    "Life shrinks or expands in proportion to one's courage.",
    "Strive not to be a success, but rather to be of value.",
    "The best dreams happen when you're awake.",
    "Opportunities don't happen. You create them.",
    "It's not whether you get knocked down, it's whether you get up.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Try not to become a person of success, but rather try to become a person of value.",
    "Don't be afraid to give up the good to go for the great.",
    "If you want to achieve greatness stop asking for permission.",
    "Things work out best for those who make the best of how things work out.",
    "To live a creative life, we must lose our fear of being wrong.",
    "If you are not willing to risk the usual you will have to settle for the ordinary."
];
